### ISSUE TITLE
want to join your team

### ISSUE THREAD

**Issue by fengyinchao** [starkwang/FDSHM#1]
你好，冒昧打扰了，我是华科的学生，对前端很感兴趣，但苦于没有项目做(实验室不搞这个)，所以想加入你的团队，做点实际有用的东西。

**Comment by starkwang** [comment]
嗯你好，抱歉这两天一直没有回复你。

我们团队现在人手比较充足，而且由于经常要当面交流开会什么的，所以我们原则上只接受本校学生的。。。

不过还是非常谢谢你的热情，华中科技大学有一个叫冰岩作坊的团队，之前去和他们见过面，他们也是一支很赞的团队，或许你可以尝试加入他们？

**Comment by fengyinchao** [comment]
既然这样，那就算了吧，多谢你的建议。
