### ISSUE TITLE
网站乱码严重，而且布局问题很大呀

### ISSUE THREAD

**Issue by Gmle7** [starkwang/FDSHM#10]
进网站没法做任何操作，点击按钮没有反应，请看一下是哪里有问题

**Comment by Gmle7** [comment]
是不是放弃这个项目了？不过现在二手交易是不好做，咸鱼太强大了。

**Comment by dragonly** [comment]
嗯, 有兴趣可以自己看看稍微修补一下应该可以运行. 前端一年地上一个世纪. 项目不再更新了.

**Comment by Gmle7** [comment]
好的，知道了。十分感谢



发自我的小米手机
在 dragonly <notifications@github.com>，2017年9月7日 11:57写道：

嗯, 有兴趣可以自己看看稍微修补一下应该可以运行. 前端一年地上一个世纪. 项目不再更新了.
