### ISSUE TITLE
hello,想问问项目的一些问题

### ISSUE THREAD

**Issue by Relsoul** [starkwang/FDSHM#5]
很抱歉在项目中issue问一些不太相关的问题。 请问up主做这个项目的时候路由放在angular还是后台控制的呢？angularjs仅仅做控制器用ajax获取数据嘛？那么模板中的ng-viwe是什么意思呢

**Comment by dragonly** [comment]
up主一刚。。
我反正不是up主，现在都是后端nodejs+express静态渲染，你从`app.js`里面一路可以看到整个项目的流程，后端代码在`src`里面，前端在`client`
剩下看 @starkwang 有空来可以说下
