### ISSUE TITLE
连续两次要求验证邮箱

### ISSUE THREAD

**Issue by lirenjie95** [starkwang/FDSHM#7]
1. 第一次收到验证邮件之后，已经点开激活。
2. 之后发布两个闲置，关闭窗口。
3. 再次打开的时候想再发布一个新闲置，此时再次跳出验证邮箱对话框。

不知道现在还有没有修复权限呢

**Comment by starkwang** [comment]
你重新登陆试试看？

**Comment by lirenjie95** [comment]
还是不行。。乖乖重新验证了
